data = [
    {"name": "Cristiano Ronaldo", "follower_count": 615, "description": "Calciatore", "country": "Portogallo"},
    {"name": "Lionel Messi", "follower_count": 500, "description": "Calciatore", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 430, "description": "Cantante", "country": "USA"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "Imprenditrice", "country": "USA"},
    {"name": "Dwayne Johnson", "follower_count": 395, "description": "Attore", "country": "USA"},
    {"name": "Ariana Grande", "follower_count": 380, "description": "Cantante", "country": "USA"},
    {"name": "Kim Kardashian", "follower_count": 365, "description": "Influencer", "country": "USA"},
    {"name": "Beyoncé", "follower_count": 320, "description": "Cantante", "country": "USA"},
    {"name": "Khloé Kardashian", "follower_count": 310, "description": "Influencer", "country": "USA"},
    {"name": "Justin Bieber", "follower_count": 290, "description": "Cantante", "country": "Canada"},
    {"name": "Kendall Jenner", "follower_count": 280, "description": "Modella", "country": "USA"},
    {"name": "Taylor Swift", "follower_count": 270, "description": "Cantante", "country": "USA"},
    {"name": "Virat Kohli", "follower_count": 260, "description": "Cricketer", "country": "India"},
    {"name": "Jennifer Lopez", "follower_count": 250, "description": "Cantante", "country": "USA"},
    {"name": "Nicki Minaj", "follower_count": 230, "description": "Rapper", "country": "USA"},
    {"name": "Miley Cyrus", "follower_count": 220, "description": "Cantante", "country": "USA"},
    {"name": "Neymar", "follower_count": 210, "description": "Calciatore", "country": "Brasile"},
    {"name": "Zendaya", "follower_count": 200, "description": "Attrice", "country": "USA"},
    {"name": "Kevin Hart", "follower_count": 180, "description": "Comico", "country": "USA"},
    {"name": "Cardi B", "follower_count": 170, "description": "Rapper", "country": "USA"},
    {"name": "LeBron James", "follower_count": 160, "description": "Cestista", "country": "USA"},
    {"name": "Shakira", "follower_count": 155, "description": "Cantante", "country": "Colombia"},
    {"name": "Drake", "follower_count": 150, "description": "Rapper", "country": "Canada"},
    {"name": "Chris Brown", "follower_count": 145, "description": "Cantante", "country": "USA"},
    {"name": "Ellen DeGeneres", "follower_count": 140, "description": "Conduttrice", "country": "USA"},
    {"name": "Rihanna", "follower_count": 135, "description": "Cantante", "country": "Barbados"},
    {"name": "Katy Perry", "follower_count": 130, "description": "Cantante", "country": "USA"},
    {"name": "Billie Eilish", "follower_count": 125, "description": "Cantante", "country": "USA"},
    {"name": "Emma Watson", "follower_count": 120, "description": "Attrice", "country": "UK"},
    {"name": "Tom Holland", "follower_count": 115, "description": "Attore", "country": "UK"},
    {"name": "Will Smith", "follower_count": 110, "description": "Attore", "country": "USA"},
    {"name": "Jason Statham", "follower_count": 105, "description": "Attore", "country": "UK"},
    {"name": "Zac Efron", "follower_count": 100, "description": "Attore", "country": "USA"},
    {"name": "Chris Hemsworth", "follower_count": 98, "description": "Attore", "country": "Australia"},
    {"name": "Gal Gadot", "follower_count": 95, "description": "Attrice", "country": "Israele"},
    {"name": "Margot Robbie", "follower_count": 90, "description": "Attrice", "country": "Australia"},
    {"name": "Robert Downey Jr.", "follower_count": 88, "description": "Attore", "country": "USA"},
    {"name": "Scarlett Johansson", "follower_count": 85, "description": "Attrice", "country": "USA"},
    {"name": "Johnny Depp", "follower_count": 82, "description": "Attore", "country": "USA"},
    {"name": "Leonardo DiCaprio", "follower_count": 80, "description": "Attore", "country": "USA"},
    {"name": "Brad Pitt", "follower_count": 78, "description": "Attore", "country": "USA"},
    {"name": "Angelina Jolie", "follower_count": 75, "description": "Attrice", "country": "USA"},
    {"name": "Keanu Reeves", "follower_count": 70, "description": "Attore", "country": "Canada"},
    {"name": "Tom Cruise", "follower_count": 68, "description": "Attore", "country": "USA"},
    {"name": "Vin Diesel", "follower_count": 65, "description": "Attore", "country": "USA"},
    {"name": "Paul Walker", "follower_count": 60, "description": "Attore", "country": "USA"},
    {"name": "Ed Sheeran", "follower_count": 95, "description": "Cantante", "country": "UK"},
    {"name": "Harry Styles", "follower_count": 92, "description": "Cantante", "country": "UK"},
    {"name": "Dua Lipa", "follower_count": 90, "description": "Cantante", "country": "UK"},
    {"name": "The Weeknd", "follower_count": 88, "description": "Cantante", "country": "Canada"},
    {"name": "Post Malone", "follower_count": 85, "description": "Rapper", "country": "USA"},
    {"name": "Travis Scott", "follower_count": 83, "description": "Rapper", "country": "USA"},
    {"name": "Doja Cat", "follower_count": 80, "description": "Cantante", "country": "USA"},
    {"name": "Olivia Rodrigo", "follower_count": 78, "description": "Cantante", "country": "USA"},
    {"name": "Bad Bunny", "follower_count": 75, "description": "Rapper", "country": "Puerto Rico"},
    {"name": "J Balvin", "follower_count": 73, "description": "Cantante", "country": "Colombia"},
    {"name": "Maluma", "follower_count": 70, "description": "Cantante", "country": "Colombia"},
    {"name": "Anitta", "follower_count": 68, "description": "Cantante", "country": "Brasile"},
    {"name": "Shawn Mendes", "follower_count": 65, "description": "Cantante", "country": "Canada"},
    {"name": "Camila Cabello", "follower_count": 63, "description": "Cantante", "country": "Cuba"},
    {"name": "Lana Del Rey", "follower_count": 60, "description": "Cantante", "country": "USA"},
    {"name": "Snoop Dogg", "follower_count": 58, "description": "Rapper", "country": "USA"},
    {"name": "Eminem", "follower_count": 55, "description": "Rapper", "country": "USA"},
    {"name": "50 Cent", "follower_count": 53, "description": "Rapper", "country": "USA"},
    {"name": "Ice Cube", "follower_count": 50, "description": "Rapper", "country": "USA"},
    {"name": "Conor McGregor", "follower_count": 47, "description": "Lottatore", "country": "Irlanda"},
    {"name": "Khabib Nurmagomedov", "follower_count": 45, "description": "Lottatore", "country": "Russia"},
    {"name": "Usain Bolt", "follower_count": 43, "description": "Atleta", "country": "Giamaica"},
    {"name": "Michael Phelps", "follower_count": 40, "description": "Nuotatore", "country": "USA"},
    {"name": "Serena Williams", "follower_count": 38, "description": "Tennista", "country": "USA"},
    {"name": "Roger Federer", "follower_count": 35, "description": "Tennista", "country": "Svizzera"},
    {"name": "Rafael Nadal", "follower_count": 34, "description": "Tennista", "country": "Spagna"},
    {"name": "Novak Djokovic", "follower_count": 33, "description": "Tennista", "country": "Serbia"}
]